# Generated by Django 4.2.24 on 2026-09-12 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TallyIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('connector_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('connector_name', models.CharField(blank=True, default='', max_length=255)),
                ('pairing_code', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('pairing_code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('auth_token', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('pairing', 'Pairing Pending'), ('connected', 'Connected'), ('offline', 'Offline'), ('error', 'Error')], default='disconnected', max_length=50)),
                ('tally_company_name', models.CharField(blank=True, default='', max_length=255)),
                ('tally_company_identifier', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('available_companies', models.JSONField(blank=True, default=list, help_text='List of detected Tally companies')),
                ('tally_version', models.CharField(blank=True, default='', max_length=100)),
                ('tally_host', models.CharField(default='http://localhost:9000', max_length=255)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_checkpoint', models.CharField(blank=True, default='', help_text='Checkpoint AlterID or sync timestamp', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tally_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tally Integration',
                'verbose_name_plural': 'Tally Integrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TallyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tally_company_identifier', models.CharField(db_index=True, max_length=255)),
                ('tally_guid', models.CharField(db_index=True, help_text='Unique Tally GUID / Voucher Master ID', max_length=255)),
                ('tally_alter_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('voucher_number', models.CharField(db_index=True, max_length=150)),
                ('voucher_type', models.CharField(default='Sales', max_length=100)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('party_name', models.CharField(db_index=True, help_text='Party name as received from Tally', max_length=255)),
                ('party_ledger_id', models.CharField(blank=True, default='', help_text='Tally Ledger GUID for Phase 2 mapping', max_length=255)),
                ('gstin', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('billing_address', models.TextField(blank=True, default='')),
                ('shipping_address', models.TextField(blank=True, default='')),
                ('reference_number', models.CharField(blank=True, default='', max_length=150)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=20)),
                ('narration', models.TextField(blank=True, default='')),
                ('sync_status', models.CharField(default='synced', max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Full raw invoice data for audit/debugging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tally.tallyintegration')),
            ],
            options={
                'verbose_name': 'Tally Invoice',
                'verbose_name_plural': 'Tally Invoices',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TallySyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('scheduled', 'Scheduled')], default='manual', max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='running', max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_details', models.TextField(blank=True, default='')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='tally.tallyintegration')),
            ],
            options={
                'verbose_name': 'Tally Sync Log',
                'verbose_name_plural': 'Tally Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TallySyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(choices=[('full_sync', 'Full Sync'), ('incremental_sync', 'Incremental Sync'), ('company_refresh', 'Company Refresh')], default='full_sync', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='tally.tallyintegration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TallyInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField(blank=True, default='')),
                ('hsn_code', models.CharField(blank=True, default='', max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, default=0.0, max_digits=12)),
                ('unit', models.CharField(blank=True, default='Nos', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('cess_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('ledger_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tally.tallyinvoice')),
            ],
            options={
                'verbose_name': 'Tally Invoice Item',
                'verbose_name_plural': 'Tally Invoice Items',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='tallyinvoice',
            constraint=models.UniqueConstraint(fields=('integration', 'tally_company_identifier', 'tally_guid'), name='unique_tally_invoice_per_company'),
        ),
    ]
