# Generated by Django 4.2.24 on 2026-09-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tally', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallysyncjob',
            name='end_date',
            field=models.DateField(blank=True, help_text='Voucher date range end filter', null=True),
        ),
        migrations.AddField(
            model_name='tallysyncjob',
            name='start_date',
            field=models.DateField(blank=True, help_text='Voucher date range start filter', null=True),
        ),
        migrations.AddField(
            model_name='tallysynclog',
            name='end_date',
            field=models.DateField(blank=True, help_text='Sync date range end', null=True),
        ),
        migrations.AddField(
            model_name='tallysynclog',
            name='start_date',
            field=models.DateField(blank=True, help_text='Sync date range start', null=True),
        ),
        migrations.AlterField(
            model_name='tallysyncjob',
            name='job_type',
            field=models.CharField(choices=[('full_sync', 'Full Sync'), ('date_range_sync', 'Date Range Sync'), ('incremental_sync', 'Incremental Sync'), ('company_refresh', 'Company Refresh')], default='full_sync', max_length=50),
        ),
    ]
