# Generated by Django 4.2.24 on 2026-07-27 09:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0008_leadfollowup_products_interested'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True, verbose_name='Product ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Code')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='HSN/SAC Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantity')),
                ('unit', models.CharField(default='NOS', max_length=20, verbose_name='Unit')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Price')),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='GST %')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_with_gst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quotationlowsideitem',
            name='quotation_version',
        ),
        migrations.RemoveField(
            model_name='quotationserviceitem',
            name='quotation_version',
        ),
        migrations.RemoveField(
            model_name='quotationserviceitem',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='quotationversion',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='site_name',
        ),
        migrations.AddField(
            model_name='quotation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotation',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst_type',
            field=models.CharField(choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST')], default='CGST_SGST', max_length=20, verbose_name='GST Type'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='industry_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry Type'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='linkedin_profile_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='LinkedIn Profile URL'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quotation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Quotation Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='lead_management.customer'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='thank_you_note',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Thank You Note'),
        ),
        migrations.AlterField(
            model_name='quotationversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quotationversion',
            name='gst_type',
            field=models.CharField(choices=[('CGST_SGST', 'CGST + SGST'), ('IGST', 'IGST')], default='CGST_SGST', max_length=20, verbose_name='GST Type'),
        ),
        migrations.AlterField(
            model_name='quotationversion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='quotationversion',
            name='version_no',
            field=models.CharField(max_length=100, verbose_name='Version Number'),
        ),
        migrations.DeleteModel(
            name='QuotationHighSideItem',
        ),
        migrations.DeleteModel(
            name='QuotationLowSideItem',
        ),
        migrations.DeleteModel(
            name='QuotationServiceItem',
        ),
        migrations.DeleteModel(
            name='ServiceMaster',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='quotation_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotation.quotationversion'),
        ),
    ]
