# Generated by Django 4.2.24 on 2026-07-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0008_leadfollowup_products_interested'),
        ('quotation', '0002_quotationitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='lead_management.lead_management'),
        ),
    ]
