# Generated by Django 4.2.24 on 2026-07-27 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_quotation_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='customer',
        ),
    ]
