# Generated by Django 4.2.24 on 2026-07-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_alter_quotationitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='msme_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MSME Number'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Number'),
        ),
    ]
