# Generated by Django 4.2.24 on 2026-07-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_termcategory_termsconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='terms_and_conditions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Terms & Conditions'),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='terms_and_conditions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Terms & Conditions'),
        ),
    ]
