# Generated by Django 4.2.24 on 2026-07-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_quotation_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='quotationversion',
            name='terms_and_conditions',
        ),
        migrations.AddField(
            model_name='quotation',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
