# Generated by Django 4.2.24 on 2026-07-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0009_remove_quotation_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='terms_and_conditions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Terms & Conditions'),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='terms_and_conditions',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Terms & Conditions'),
        ),
    ]
