# Generated by Django 4.2.24 on 2026-08-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0010_quotation_terms_and_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='Is Finalized'),
        ),
        migrations.AddField(
            model_name='quotationversion',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='Is Finalized'),
        ),
    ]
