# Generated by Django 4.2.24 on 2026-08-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_quotation_is_finalized_quotationversion_is_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_dropped',
            field=models.BooleanField(default=False, verbose_name='Is Dropped'),
        ),
    ]
