# Generated by Django 4.2.24 on 2026-09-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0012_quotation_is_dropped'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='quotation_for',
            field=models.CharField(choices=[('Ahilyanagar', 'Ahilyanagar'), ('Pune', 'Pune')], default='Pune', max_length=50, verbose_name='Quotation For'),
        ),
    ]
