# Generated by Django 4.2.24 on 2026-09-17 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotation', '0013_quotation_quotation_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name='Account Holder Name')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('account_type', models.CharField(choices=[('Current', 'Current Account'), ('Savings', 'Savings Account'), ('CC', 'Cash Credit (CC)'), ('OD', 'Overdraft (OD)')], default='Current', max_length=50, verbose_name='Account Type')),
                ('ifsc_code', models.CharField(max_length=20, verbose_name='IFSC Code')),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch Name')),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='UPI ID')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='billing/qr_codes/', verbose_name='QR Code Image')),
                ('swift_code', models.CharField(blank=True, max_length=30, null=True, verbose_name='SWIFT / BIC Code')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Beneficiary / Company Name')),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='GSTIN')),
                ('pan_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='PAN Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Payment Instructions / Notes')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Primary / Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_details_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing Detail',
                'verbose_name_plural': 'Billing Details',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='billing_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='quotation.billingdetail', verbose_name='Billing Detail'),
        ),
    ]
