# Generated by Django 4.2.24 on 2026-08-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0005_alter_amccycle_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amccontract',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'AMC Contract', 'verbose_name_plural': 'AMC Contracts'},
        ),
    ]
