# Generated by Django 4.2.24 on 2026-07-17 10:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product / Service Name')),
                ('product_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Product Code')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Price (₮)')),
                ('hsn_sac_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='HSN / SAC Code')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Product Description')),
                ('product_image_url', models.URLField(blank=True, help_text='Leave blank for auto icon', max_length=500, null=True, verbose_name='Product Image URL')),
                ('gst_type', models.CharField(choices=[('GST', 'GST'), ('IGST', 'IGST'), ('CGST_SGST', 'CGST + SGST'), ('EXEMPT', 'Exempt'), ('NIL', 'Nil Rated')], default='GST', max_length=20)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_service', models.BooleanField(default=False)),
                ('extra_attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product_management.category', verbose_name='Category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
