# Generated by Django 4.2.24 on 2026-09-10 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('category', models.CharField(choices=[('lead', 'Leads / Enquiries'), ('customer', 'Customers'), ('followup', 'Follow-up Management'), ('quotation', 'Quotations'), ('project', 'Projects'), ('amc', 'AMC Contracts')], default='lead', max_length=50)),
                ('subject', models.CharField(blank=True, help_text='Email Subject line with optional placeholders', max_length=255, null=True)),
                ('body', models.TextField(help_text='Message body with optional placeholders like {customer_name}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
