# Generated by Django 4.2.24 on 2026-07-20 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Company Name')),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Mobile Number')),
                ('secondary_contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Contact')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('secondary_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Secondary Email')),
                ('poc_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Person')),
                ('poc_contact_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Contact Person Number')),
                ('land_line_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Landline Number')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Pincode')),
                ('linkedin_profile_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='LinkedIn Profile URL')),
                ('industry_type', models.CharField(blank=True, choices=[('it_services', 'IT Services'), ('manufacturing', 'Manufacturing'), ('banking', 'Banking'), ('automotive', 'Automotive'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('real_estate', 'Real Estate')], max_length=50, null=True, verbose_name='Industry Type')),
                ('both_address_is_same', models.BooleanField(default=False, verbose_name='Site Address Same as Billing')),
                ('site_address', models.TextField(blank=True, null=True, verbose_name='Site Address')),
                ('site_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site City')),
                ('site_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Site State')),
                ('site_pin_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Site Pincode')),
                ('gst', models.CharField(blank=True, max_length=15, null=True, verbose_name='GST Number')),
                ('pan', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Number')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='lead_management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_date', models.DateField(blank=True, null=True, verbose_name='Lead Date')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('linkedin_profile_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='LinkedIn Profile URL')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('product_interested', models.JSONField(blank=True, default=list, null=True, verbose_name='Product Interested')),
                ('expected_closure_date', models.DateField(blank=True, null=True, verbose_name='Expected Closure Date')),
                ('lead_source', models.CharField(blank=True, choices=[('website', 'Website'), ('referral', 'Referral'), ('cold_call', 'Cold Call'), ('social_media', 'Social Media'), ('email_campaign', 'Email Campaign'), ('exhibition', 'Exhibition')], max_length=50, null=True, verbose_name='Lead Source')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='Contact Person')),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('industry_type', models.CharField(blank=True, choices=[('it_services', 'IT Services'), ('manufacturing', 'Manufacturing'), ('banking', 'Banking'), ('automotive', 'Automotive'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('real_estate', 'Real Estate')], max_length=50, null=True, verbose_name='Industry Type')),
                ('expected_budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='Expected Budget')),
                ('priority', models.CharField(blank=True, choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=50, null=True, verbose_name='Priority')),
                ('followup_date', models.DateField(blank=True, null=True, verbose_name='Follow-up Date')),
                ('pipeline_stage', models.CharField(choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('requirement_gathering', 'Requirement Gathering'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation')], default='new_lead', max_length=50, verbose_name='Pipeline Stage')),
                ('is_tally_user', models.CharField(blank=True, max_length=10, null=True, verbose_name='Is Tally User')),
                ('requirement_details', models.TextField(blank=True, null=True, verbose_name='Requirement Details')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_process', 'In Process')], default='open', max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_qualified', models.BooleanField(default=False, verbose_name='Is Qualified')),
                ('qualifying_answers', models.JSONField(blank=True, default=dict, null=True, verbose_name='Qualifying Answers')),
                ('is_converted', models.BooleanField(default=False, verbose_name='Is Converted')),
                ('assigned_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Executive')),
                ('converted_to_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_lead', to='lead_management.customer', verbose_name='Converted To Customer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_date', models.DateField()),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_process', 'In Process')], default='open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_followups_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='lead_management.lead_management')),
            ],
        ),
        migrations.CreateModel(
            name='LeadFollowUpFAQAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True)),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lead_management.leadfaq')),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_answers', to='lead_management.leadfollowup')),
            ],
            options={
                'unique_together': {('followup', 'faq')},
            },
        ),
    ]
