# Generated by Django 4.2.24 on 2026-07-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['customer_code']},
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='poc_name',
            new_name='contact_person',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='gst',
            new_name='gst_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='poc_contact_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Customer Code'),
        ),
        migrations.AddField(
            model_name='customer',
            name='product_purchased',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Product Purchased'),
        ),
        migrations.AddField(
            model_name='customer',
            name='service_package',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Service Package'),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number'),
        ),
    ]
