# Generated by Django 4.2.24 on 2026-07-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0002_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='industry_type',
            field=models.CharField(blank=True, choices=[('it_services', 'IT Services'), ('manufacturing', 'Manufacturing'), ('banking', 'Banking'), ('automotive', 'Automotive'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('real_estate', 'Real Estate'), ('other', 'Other')], max_length=50, null=True, verbose_name='Industry Type'),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='industry_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Industry Type'),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='lead_source',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lead Source'),
        ),
    ]
