# Generated by Django 4.2.24 on 2026-07-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0003_alter_customer_industry_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadfollowup',
            name='remarks',
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='additional_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Remarks'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='budget_status',
            field=models.CharField(blank=True, choices=[('approved', 'Budget Approved'), ('allocated', 'Budget Allocated (not approved)'), ('under_discussion', 'Budget Under Discussion'), ('no_budget', 'No Budget Yet'), ('not_disclosed', 'Not Disclosed')], max_length=50, null=True, verbose_name='Budget Status'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='client_response',
            field=models.CharField(blank=True, choices=[('very_positive', 'Very Positive'), ('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative'), ('no_response', 'No Response'), ('call_back_later', 'Call Back Later')], max_length=50, null=True, verbose_name='Client Response'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='commitment_client',
            field=models.TextField(blank=True, null=True, verbose_name='Commitment by Client'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='commitment_us',
            field=models.TextField(blank=True, null=True, verbose_name='Commitment by Us'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='competition',
            field=models.TextField(blank=True, null=True, verbose_name='Competition (Other Vendors Evaluated)'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='competitors_list',
            field=models.TextField(blank=True, null=True, verbose_name='e.g. SAP, Zoho, Tally, None'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='current_stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('requirement_gathering', 'Requirement Gathering'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new_lead', max_length=50, verbose_name='Current Stage'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='decision_maker_contacted',
            field=models.CharField(blank=True, choices=[('yes_final', 'Yes — Final Decision Maker'), ('yes_influencer', 'Yes — Influencer / Recommender'), ('no_need_higher', 'No — Need to Reach Higher')], max_length=50, null=True, verbose_name='Decision Maker Contacted'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='discussion_summary',
            field=models.TextField(blank=True, null=True, verbose_name='Discussion Summary'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='followup_mode',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('video_call', 'Video Call'), ('in_person', 'In-Person'), ('demo', 'Demo'), ('site_visit', 'Site Visit')], max_length=50, null=True, verbose_name='Follow-up Mode'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='followup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Follow-up Time'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='move_to_stage',
            field=models.CharField(blank=True, choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('requirement_gathering', 'Requirement Gathering'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('on_hold', 'On Hold')], max_length=50, null=True, verbose_name='Move to Next Stage'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='next_followup_mode',
            field=models.CharField(blank=True, choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('video_call', 'Video Call'), ('in_person', 'In-Person'), ('demo', 'Demo'), ('site_visit', 'Site Visit')], max_length=50, null=True, verbose_name='Next Follow-up Mode'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='number_of_users',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Number of Users (Confirmed)'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='pain_point_urgency',
            field=models.CharField(blank=True, choices=[('critical', 'Critical — Impacting Business'), ('moderate', 'Moderate — Manageable but needs fix'), ('low', 'Low — Nice to have')], max_length=50, null=True, verbose_name='Pain Point / Problem Urgency'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='ready_to_send_quotation',
            field=models.BooleanField(default=False, verbose_name='Ready to send a quotation'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='timeline_urgency',
            field=models.CharField(blank=True, choices=[('immediate', 'Immediate (within 1 month)'), ('short_term', 'Short-term (1–3 months)'), ('mid_term', 'Mid-term (3–6 months)'), ('long_term', 'Long-term (6+ months)'), ('no_clear', 'No Clear Timeline')], max_length=50, null=True, verbose_name='Timeline / Urgency'),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='followup_date',
            field=models.DateField(verbose_name='Follow-up Date'),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='next_followup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Next Follow-up Date'),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_process', 'In Process')], default='open', max_length=50, verbose_name='Status'),
        ),
    ]
