# Generated by Django 4.2.24 on 2026-07-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0004_remove_leadfollowup_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfollowup',
            name='followup_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Follow-up Number'),
        ),
    ]
