# Generated by Django 4.2.24 on 2026-07-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0005_leadfollowup_followup_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfollowup',
            name='followup_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Follow-up Number'),
        ),
    ]
