# Generated by Django 4.2.24 on 2026-07-20 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead_management', '0006_alter_leadfollowup_followup_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pan',
            new_name='pan_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='both_address_is_same',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='industry_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='land_line_no',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='linkedin_profile_url',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='secondary_contact_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='secondary_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='site_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='site_city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='site_pin_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='site_state',
        ),
        migrations.AddField(
            model_name='customer',
            name='amc_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='AMC End Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='amc_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='AMC Start Date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.TextField(blank=True, verbose_name='Billing Address'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_status',
            field=models.CharField(choices=[('prospect', 'Prospect'), ('active', 'Active'), ('inactive', 'Inactive'), ('on_hold', 'On Hold')], default='prospect', max_length=50, verbose_name='Customer Status'),
        ),
        migrations.AddField(
            model_name='customer',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation'),
        ),
        migrations.AddField(
            model_name='customer',
            name='industry_category',
            field=models.CharField(blank=True, choices=[('it_services', 'IT Services'), ('manufacturing', 'Manufacturing'), ('banking', 'Banking'), ('automotive', 'Automotive'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('real_estate', 'Real Estate'), ('other', 'Other')], max_length=50, null=True, verbose_name='Industry Category'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, choices=[('advance', 'Advance'), ('partial', 'Partial'), ('credit', 'Credit'), ('milestone', 'Milestone'), ('upon_completion', 'Upon Completion')], max_length=50, null=True, verbose_name='Payment Terms'),
        ),
        migrations.AddField(
            model_name='customer',
            name='project_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Project Value'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_sales', to=settings.AUTH_USER_MODEL, verbose_name='Sales Executive'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
