# Generated by Django 4.2.24 on 2026-07-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0007_rename_pan_customer_pan_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadfollowup',
            name='products_interested',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Products Interested'),
        ),
    ]
