# Generated by Django 4.2.24 on 2026-07-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0008_leadfollowup_products_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='msme_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MSME Number'),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GST Number'),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='msme_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='MSME Number'),
        ),
        migrations.AddField(
            model_name='lead_management',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Number'),
        ),
    ]
