# Generated by Django 4.2.24 on 2026-07-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0009_customer_msme_number_lead_management_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='leadfollowup',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Amount'),
        ),
    ]
