# Generated by Django 4.2.24 on 2026-07-30 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0010_lead_management_amount_leadfollowup_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_customer_records', to='lead_management.lead_management', verbose_name='Converted From Lead'),
        ),
    ]
