# Generated by Django 4.2.24 on 2026-07-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0011_customer_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
