# Generated by Django 4.2.24 on 2026-08-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0012_lead_management_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='pipeline_stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('requirement_gathering', 'Requirement Gathering'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='new_lead', max_length=50, verbose_name='Pipeline Stage'),
        ),
    ]
