# Generated by Django 4.2.24 on 2026-08-01 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0013_alter_lead_management_pipeline_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead_management',
            name='pipeline_stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('requirement_gathering', 'Requirement Gathering'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation')], default='new_lead', max_length=50, verbose_name='Pipeline Stage'),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close_win', 'Close Win'), ('close_loss', 'Close Loss')], default='open', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='current_stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('requirement_gathering', 'Requirement Gathering'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation')], default='new_lead', max_length=50, verbose_name='Current Stage'),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='move_to_stage',
            field=models.CharField(blank=True, choices=[('new_lead', 'New Lead'), ('contacted', 'Contacted'), ('requirement_gathering', 'Requirement Gathering'), ('demo_scheduled', 'Demo Scheduled'), ('demo_completed', 'Demo Completed'), ('proposal_sent', 'Proposal Sent'), ('negotiation', 'Negotiation')], max_length=50, null=True, verbose_name='Move to Next Stage'),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close_win', 'Close Win'), ('close_loss', 'Close Loss')], default='open', max_length=50, verbose_name='Status'),
        ),
    ]
