# Generated by Django 4.2.24 on 2026-08-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0014_alter_lead_management_pipeline_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='last_followup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Follow-up Date'),
        ),
    ]
