# Generated by Django 4.2.24 on 2026-08-01 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lead_management', '0015_lead_management_last_followup_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Project Code')),
                ('product', models.JSONField(blank=True, default=list, null=True, verbose_name='Product(s)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('expected_to_go_live', models.DateField(blank=True, null=True, verbose_name='Expected to Go Live')),
                ('project_stage', models.CharField(choices=[('requirement_analysis', 'Requirement Analysis'), ('installation', 'Installation'), ('data_migration', 'Data Migration'), ('customization', 'Customization'), ('training', 'Training'), ('uat', 'UAT'), ('go_live', 'Go Live')], default='requirement_analysis', max_length=50, verbose_name='Project Stage')),
                ('no_of_user', models.CharField(blank=True, max_length=50, null=True, verbose_name='Number of Users')),
                ('project_value', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, verbose_name='Project Value')),
                ('project_scope_requirements', models.TextField(blank=True, null=True, verbose_name='Project Scope / Requirements')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=50, verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='lead_management.customer', verbose_name='Customer')),
                ('project_executive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Project Executive')),
                ('team_members', models.ManyToManyField(blank=True, related_name='team_projects', to=settings.AUTH_USER_MODEL, verbose_name='Team Members')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
