# Generated by Django 4.2.24 on 2026-08-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0016_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_members',
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.TextField(blank=True, null=True, verbose_name='Team Members'),
        ),
    ]
