# Generated by Django 4.2.24 on 2026-08-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0017_remove_project_team_members_project_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead_management',
            name='tally_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tally Number'),
        ),
    ]
