# Generated by Django 4.2.24 on 2026-08-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0018_lead_management_tally_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amc_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='AMC End Date'),
        ),
        migrations.AddField(
            model_name='project',
            name='amc_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='AMC Start Date'),
        ),
    ]
