# Generated by Django 4.2.24 on 2026-08-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0020_amccontract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AMCContract',
        ),
    ]
