# Generated by Django 4.2.24 on 2026-08-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0021_delete_amccontract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead_management',
            name='is_qualified',
        ),
        migrations.RemoveField(
            model_name='lead_management',
            name='qualifying_answers',
        ),
    ]
