# Generated by Django 4.2.24 on 2026-09-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_management', '0022_remove_lead_management_is_qualified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lead_source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lead Source'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry_category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry Category'),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='industry_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry Type'),
        ),
        migrations.AlterField(
            model_name='lead_management',
            name='lead_source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lead Source'),
        ),
    ]
